"""
Django settings for otcloud project.

Generated by 'django-admin startproject' using Django 5.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1#!8p^&u+%+tfxqe!kcp7*&n*9!ujubt6ug3cr@opt29)@1#cc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'otcloud',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'otcloud.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'otcloud.context_processors.site_contact',
            ],
        },
    },
]

WSGI_APPLICATION = 'otcloud.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Media (user-uploaded files, e.g. blog cover images)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# Real delivery uses Gmail SMTP and activates automatically once EMAIL_HOST_PASSWORD
# (a Gmail App Password) is set in the environment. Without it, mail prints to the console.
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', 'otcloudcenter@gmail.com')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

if EMAIL_HOST_PASSWORD:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = 'smtp.gmail.com'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = f'OT Cloud Therapy Center <{EMAIL_HOST_USER}>'

# Where booking/contact notifications are sent
NOTIFY_EMAIL = 'otcloudcenter@gmail.com'


# Clinic contact details — surfaced to every template via context_processors.site_contact
SITE_CONTACT = {
    'phone_display': '+91 96670 83440',
    'tel': '+919667083440',
    'whatsapp_number': '919667083440',
    'whatsapp_message': "Hello, I'd like to know more about OT Cloud Therapy Center's services and book an assessment.",
    'email': 'otcloudcenter@gmail.com',
    'address': 'OT Cloud Therapy Center\nSector 14, DLF Colony, Gurugram\n(Near Main Market)',
    # Structured address parts (used for LocalBusiness JSON-LD / SEO)
    'street': 'Sector 14, DLF Colony (Near Main Market)',
    'locality': 'Gurugram',
    'region': 'Haryana',
    'postal_code': '122001',
    'country': 'IN',
    'facebook': 'https://www.facebook.com/ot.all.31?mibextid=ZbWKwL',
    'youtube': 'https://www.youtube.com/@otcloudtherapycenter',
    'instagram': 'https://www.instagram.com/ot_cloud_therapy_center/',
}

# Brand name used in SEO titles / structured data
SITE_NAME = 'OT Cloud Therapy Center'

# Top announcement / workshop bar. Edit the text/link here (or set enabled=False to hide).
SITE_ANNOUNCEMENT = {
    'enabled': False,
    'text': 'Free Parent Workshop: Managing ADHD at Home — this Saturday at our Sector 14 center.',
    'link_text': 'Reserve a seat',
    'link_url': '/contact/',
}
