# Generated by Django 5.2.16 on 2026-07-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otcloud', '0002_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='author',
            field=models.CharField(default='OT Cloud Team', max_length=120),
        ),
    ]
