# Generated by Django 5.2.16 on 2026-07-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otcloud', '0004_newslettersignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=120)),
                ('child_name', models.CharField(max_length=120)),
                ('child_age', models.CharField(blank=True, max_length=40)),
                ('phone', models.CharField(max_length=30)),
                ('area_of_concern', models.CharField(blank=True, choices=[('speech', 'Speech & Language'), ('ot', 'Occupational Therapy (Sensory/Motor)'), ('behavior', 'Behavioral Concerns'), ('autism', 'Autism Spectrum / Neurodiversity'), ('attention', 'Attention & Focus (ADHD)'), ('general', 'General Developmental Milestone Check')], max_length=20)),
                ('contact_method', models.CharField(blank=True, choices=[('phone', 'Phone'), ('whatsapp', 'WhatsApp')], max_length=10)),
                ('preferred_time', models.CharField(blank=True, choices=[('morning', 'Morning (9am - 12pm)'), ('afternoon', 'Afternoon (12pm - 4pm)'), ('evening', 'Evening (4pm - 7pm)')], max_length=12)),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Appointment enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
