# Generated by Django 5.2.16 on 2026-08-08 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otcloud', '0005_appointmentenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentenquiry',
            name='area_of_concern',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='assessmentrequest',
            name='area_of_concern',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
