# Generated by Django 5.2.16 on 2026-08-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otcloud', '0006_alter_appointmentenquiry_area_of_concern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_name', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('child_age', models.CharField(blank=True, help_text='Age band the parent selected in the milestone check.', max_length=60)),
                ('milestones_done', models.PositiveSmallIntegerField(default=0)),
                ('milestones_total', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Milestone enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
