# Generated by Django 5.2.16 on 2026-09-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otcloud', '0007_milestoneenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('child-development', 'Child Development'), ('occupational-therapy', 'Occupational Therapy'), ('speech-language', 'Speech & Language'), ('sensory-processing', 'Sensory Processing'), ('behaviour', 'Behaviour & Emotional Regulation'), ('learning', 'Learning & School Readiness'), ('parent-guides', 'Parent Guides')], default='child-development', help_text='Topic this post is filed under.', max_length=30),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='from_therapy_team',
            field=models.BooleanField(default=False, help_text='Show this post under "Insights from OTCloud".', verbose_name='Insight from the therapy team'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='key_takeaways',
            field=models.TextField(blank=True, help_text='One takeaway per line. Shown in a highlighted box under the introduction.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='kind',
            field=models.CharField(choices=[('article', 'Article — short, answers one question'), ('guide', 'Guide — longer, covers a whole topic')], default='article', max_length=10, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='reading_time',
            field=models.PositiveSmallIntegerField(default=0, help_text='Minutes. Leave at 0 to calculate it from the body.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_concern',
            field=models.CharField(blank=True, help_text='Concern to link at the end of the post, e.g. "Sensory Processing".', max_length=60),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_concern_note',
            field=models.CharField(blank=True, help_text='One line describing that concern (optional).', max_length=220),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='related_service',
            field=models.CharField(blank=True, choices=[('service_ot', 'Occupational Therapy'), ('service_speech', 'Speech and Language Therapy'), ('service_early', 'Early Intervention'), ('service_se', 'Special Education'), ('service_psychology', 'Child Psychology')], help_text='OTCloud service to link at the end of the post (optional).', max_length=30),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='start_here',
            field=models.BooleanField(default=False, help_text='Feature this post in the "Start Here" row at the top of the blog.'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='views',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Read count — drives the "Parents Are Reading" row.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(help_text='Blank lines start new paragraphs. Start a line with "## " for a section heading, "### " for a sub-heading and "- " for a bullet.'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.TextField(blank=True, help_text='Two-line summary shown on cards and as the article introduction.', max_length=300),
        ),
    ]
