# Generated by Django 5.2.16 on 2026-09-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otcloud', '0008_blogpost_category_blogpost_from_therapy_team_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='related_service',
            field=models.CharField(blank=True, choices=[('service_ot', 'Occupational Therapy'), ('service_speech', 'Speech and Language Therapy'), ('service_early', 'Early Intervention'), ('service_se', 'Special Education'), ('service_psychology', 'Child Psychology'), ('service_physio', 'Child Physiotherapy')], help_text='OTCloud service to link at the end of the post (optional).', max_length=30),
        ),
    ]
