# Generated by Django 5.2.16 on 2026-09-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('otcloud', '0009_alter_blogpost_related_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentrequest',
            name='child_age',
            field=models.CharField(blank=True, help_text='As given by the parent, e.g. "4 years 6 months".', max_length=40, verbose_name='Child age'),
        ),
    ]
