# Generated by Django 5.2.16 on 2026-09-26 17:49

from django.db import migrations, models


# Where each former Parent Guides post belongs by subject; anything else lands in
# Child Development.
PARENT_GUIDE_TOPICS = {
    'a-parents-guide-to-sensory-processing': 'sensory-processing',
    'a-parents-guide-to-school-readiness': 'learning',
    'understanding-developmental-milestones': 'child-development',
    'when-should-i-seek-a-professional-assessment': 'child-development',
}


def refile_parent_guides(apps, schema_editor):
    BlogPost = apps.get_model('otcloud', 'BlogPost')
    for post in BlogPost.objects.filter(category='parent-guides'):
        post.category = PARENT_GUIDE_TOPICS.get(post.slug, 'child-development')
        post.save(update_fields=['category'])


class Migration(migrations.Migration):

    dependencies = [
        ('otcloud', '0010_assessmentrequest_child_age'),
    ]

    operations = [
        migrations.RunPython(refile_parent_guides, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('child-development', 'Child Development'), ('occupational-therapy', 'Occupational Therapy'), ('speech-language', 'Speech & Language'), ('sensory-processing', 'Sensory Processing'), ('behaviour', 'Behaviour & Emotional Regulation'), ('learning', 'Learning & School Readiness')], default='child-development', help_text='Topic this post is filed under.', max_length=30),
        ),
    ]
